### ISSUE TITLE
exiting problem

### ISSUE THREAD

**Issue by suraj-grewal** [Jaskaranbir/MySQL_GUI#1]
problem 1 with your soft...sometimes it takes 2 times going through exiting procedure to quit... 

takes hell lot of time to load (must be my pc)

**Comment by Jaskaranbir** [comment]
The loading time is a spring framework bug. Should be fine after loading.
As for exit, I haven't been able to reproduce the problem yet. Can you perhaps check for the activity done prior to exiting to help know the cause? And are you talking about exiting from the `Close` button or the `Exit` option from `File` menu?

**Comment by suraj-grewal** [comment]
yup, ive been able to recreate it twice.

**Comment by Jaskaranbir** [comment]
How?
I mean what actions lead to this problem?
